Slhmy/move test
OJ-lab/judger pull request #86
Opened 2023-04-25 06:29 UTC by slhmy

Solve #85

2023-04-25 15:10 UTC, KanadeSiina commented
It seems good, but I think some guides should be added to `README.md` so that it could help others build the developing environment from scratch. 
BTW, though it is enough now, but I hope that we can remove the binary files as well as the `testlib.h` in the future.

2023-04-30 16:44 UTC, cubercsl requested changes

2023-04-30 16:44 UTC, cubercsl commented on .github/workflows/rust_build.yml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v3
        with:
          submodules: recursive
```

2023-04-30 16:44 UTC, cubercsl commented on .github/workflows/rust_build.yml
> +        run: git submodule update --init --recursive
```suggestion
```
submodules should be checked out by `actions/checkout`

2023-05-01 14:20 UTC, slhmy commented on .github/workflows/rust_build.yml
> +      - uses: actions/checkout@v2
Thanks for suggestion, changed.

2023-05-02 10:54 UTC, slhmy commented
I'm merging this PR right now, for the known issues can be fixed later.

2023-05-02 10:54 UTC, merged